#name: homepage

image:
  url: helm-charts/charts/adguard

ports:
  http:
    port: 
      container: 8200
      service: 80

env:
  TZ: Etc/UTC

volumes:
  config:
    path: /app/config
    configMap:
      name: homepage-config
      data:
        bookmarks.yaml:
            - Developer:
                - Github:
                    - abbr: GH
                      href: https://github.com/
        services.yaml:
          - My First Group:
              - My First Service:
                  href: http://localhost/
                  description: Homepage is awesome

          - My Second Group:
              - My Second Service:
                  href: http://localhost/
                  description: Homepage is the best

          - My Third Group:
              - My Third Service:
                  href: http://localhost/
                  description: Homepage is 😎
        widgets.yaml:
          - resources:
              # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
              backend: resources
              expanded: true
              cpu: true
              memory: true
          - search:
              provider: duckduckgo
              target: _blank
          ## Uncomment to enable Kubernetes integration
          # - kubernetes:
          #     cluster:
          #       show: true
          #       cpu: true
          #       memory: true
          #       showLabel: true
          #       label: "cluster"
          #     nodes:
          #       show: true
          #       cpu: true
          #       memory: true
          #       showLabel: true
        kubernetes.yaml:
          # change mode to 'cluster' to use RBAC service account
          mode: disable
        docker.yaml: ""
        settings.yaml: ""

#ha:
#  probe:
#    port: http
#    path: /ngax/index.html