image:
  url: lscr.io/linuxserver/duplicati:latest

ports:
  http:
    port: 
      container: 8200
      service: 80

env:
  TZ: Etc/UTC
  SETTINGS_ENCRYPTION_KEY: verysecret

volumes:
  config:
    pvc: config
    path: /config
  source:
    pvc: source
    path: /source

ha:
  probe:
    port: http
    path: /ngax/index.html