name: duplicati

image:
  url: lscr.io/linuxserver/duplicati
  version: latest

ports:
  http:
    port: 
      container: 8200
      service: 80

env:
  TZ: Etc/UTC
  SETTINGS_ENCRYPTION_KEY: verysecret

volumes:
  config:
    pvc: config
    path: /config

ha:
  probe:
    port: http
    path: /ngax/index.html