apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ include "service.namespace" . }}
spec:
  defaultBackend:
    service:
      name: {{ include "service.name" . }}
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - {{ .Values.tailscale.dns }}
