apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: downloads
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.downloads.path }}
    server: {{ .Values.downloads.ip }}
    readOnly: false
  mountOptions:
    - nfsvers=3
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: downloads
